typography_spectrum: 0.4786126301623881
color:
  brandStrength: 0.31098323385231197
  lightness: 0.9950805131811649
  saturation: 0.22309544566087425
  rhythmicContrast: 0.46920398413203657
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
layout_spectrum: 0.08565982384607196
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/80d72413-db66-4608-86e3-eaa38fd5dc4c.png
name: Agencija Connect Usluge
url: 'https://usluge.connect365.online'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Home
    url: 'http://connect365.online/'
    type: external
  - name: Portfolio
    url: 'http://portfolio.connect365.online/'
    type: external
  - name: Blog
    url: 'http://blog.connect365.online/'
    type: external
  - name: Kontakt
    url: 'http://connect365.online/o-nama'
    type: external
  - name: Zanimljivosti
    url: 'http://zanimljivosti.connect365.online/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cd0b97ee-9c86-4d4e-9e94-5343fee610c4.png
title: Ovo su naše usluge
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ced485dd-d874-4894-be65-46374eb245d4.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ced485dd-d874-4894-be65-46374eb245d4.gif
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Grafički i Web dizajn, Internet oglašavanje'
purpose:
  - type: contact
    url: 'tel:+38763313588'
    label: Call +38763313588
